import { ParticleSensor } from './particlesensor';
import { UnitOfMeasure } from './unitofmeasure';
import { DataPointMetric } from './datapointmetric';

export class FormattedSensorReadingsResponse {
  sn: string;
  at: string;
  at2: string;
  ah: string;
  st: string;
  t: string;
  ta: string;
  p: string;
  pa: string;
  p2: string;
  p2a: string;
  c: string;
  f: string;
  ll: string;
  bl: string;
  slm: string;
  sls: string;
  slt: string;
  sw1: string;
  sw2: string;
  sw3: string;
  sm1: string;
  sm2: string;
  sm3: string;
  sm4: string;
  sm5: string;
  st1: string;
  st2: string;
  st3: string;
  st4: string;
  se1: string;
  se2: string;
  se3: string;
  se4: string;
  vpd: string;
  gp1: string;
  gp2: string;
  gp3: string;
  gp4: string;
  gp5: string;
  gp6: string;
  gp7: string;
  gp8: string;
  do: string;
  fr: string;
  ot: string;
  oh: string;
  ov: string;
  oa: string;
  pc: string;
  pr: string;
  wd: string;
  ws: string;
  a1: string;
  a2: string;
  a3: string;
  a4: string;
  a5: string;
  a6: string;
  a7: string;
  a8: string;
  cl1: string;
  cl2: string;
  cl3: string;
  cl4: string;
  cl5: string;
  b1: string;
  b2: string;
  b3: string;
  b4: string;
  b5: string;
  b6: string;
  b7: string;
  b8: string;
  sms: string;
  sts: string;
  ses: string;
  ssn: string;
  ts: Date;
  ct?: number;
}

export class SensorSummariesResponse {
  SensorId: string;
  Name: string;
  ParticleSensor: ParticleSensor;
  UnitOfMeasure?: UnitOfMeasure;
  DataPointMetric?: DataPointMetric;
  MinValue: number;
  MaxValue: number;
}
